apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    version: latest
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: docker.io/smita0208/hello_flask_app:latest
        name: flask-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}