apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    version: latesta55c4539-3a98-42ca-8b71-caa43afa51d8
  name: flask-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: docker.io/smita0208/flask-app:latesta55c4539-3a98-42ca-8b71-caa43afa51d8
        name: flask-app
        ports:
        - containerPort: 80
        resources: {}
status: {}