apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    version: latest4ac30585-3a77-418b-8226-e65e2ca4a00d
  name: flask-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: docker.io/smita0208/flask-app:latest4ac30585-3a77-418b-8226-e65e2ca4a00d
        name: flask-app
        ports:
        - containerPort: 80
        resources: {}
status: {}