apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: flask-app
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  type: LoadBalancer