version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

# Defining my jobs
jobs:
  build-flask: #Docker build job which uses make file to install and lint
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
      
    steps:
      - checkout
      - run:
          name: verify the system
          command: |
            ls -Rla ~/
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

# this workflow builds docker image ,pushes to docker hub and uses rolling update to update image          
workflows:
  build:
    jobs:
      - build-flask
      - docker/hadolint:
          trusted-registries: docker.io
          requires: [build-flask]
      #publishes docker image to docker hub
      - docker/publish:
          attach-at: './'
          image: ${DOCKERHUB_USER}/flask-app
          tag: latest${CIRCLE_WORKFLOW_ID}
          context: capstone
          requires:
            - docker/hadolint
      #updates container image using rolling update strategy
      - aws-eks/update-container-image:
          aws-region: us-west-2
          cluster-name: capstone
          container-image-updates: flask-app=docker.io/${DOCKERHUB_USER}/flask-app:latest${CIRCLE_WORKFLOW_ID}
          get-rollout-status: true
          namespace: flask-app
          resource-name: deployment/flask-app
          record: true
          show-kubectl-command: true
          watch-timeout: 10m
          requires:
            - "docker/publish"